library(shiny)
library(shinyjs)
library(ggplot2)
library(GGally)
library(DT)
library(tidyverse)
library(lubridate)
library(shinycssloaders)
library(viridis)
library(visdat)
library(corrgram)
library(vcd)
library(summarytools)
library(car)


dat <- read.csv("Ass1Data.csv", header = TRUE, stringsAsFactors = TRUE)

choicesA <- colnames(as.data.frame(dat))
choicesA <- choicesA[-length(choicesA)]
namesmosaic <- colnames(dat[,c(3, 5:14)])
mosaicchoices <- colnames(dat[,c(5:8)])
boxnames <- colnames(dat[,c(1, 15:44)])
boxchoices <- colnames(dat[,c(1, 15:18)])
mischoices <- colnames(dat[,c(15:24)])
namescorr <- colnames(dat[-c(2:14)])
corrchoices <- colnames(dat[,c(15:24)])
valuechoices <- colnames(dat[c(1)])
pairsnames <- colnames(dat[-c(2)])
pairschoices <- colnames(dat[,c(11:15)])
morecolours <- colnames(dat[,c(3, 5:14)])

dat$Date <- ymd(dat$Date)
dat$Priority <- ordered(dat$Priority, c("Low", "Medium", "High"))
dat$Price <- ordered(dat$Price, c("Cheap", "Fair", "Expensive"))
dat$Speed <- ordered(dat$Speed, c("Slow", "Medium", "Fast"))
dat$Duration <- ordered(dat$Duration, c("Short", "Long", "Very Long"))
dat$Temp <- ordered(dat$Temp, c("Cold", "Warm", "Hot"))
dat$Surface <- ordered(dat$Surface, c("Smooth", "Textured", "Rough"))
